// Code generated by enthistory, DO NOT EDIT.

package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/flume/enthistory"
)

type TestEntityHistory struct {
	ent.Schema
}

func (TestEntityHistory) Fields() []ent.Field {
	return []ent.Field{
		field.Time("history_time").
			Immutable().
			Default(time.Now),
		field.Enum("operation").
			Immutable().
			GoType(enthistory.OpType("")),
		field.Int("ref").
			Optional().
			Immutable(),
		field.Int("updated_by").
			Nillable().
			Optional().
			Immutable(),
		field.Enum("status").
			Immutable().
			Default("started").
			Values("started", "success")}
}
func (TestEntityHistory) Edges() []ent.Edge {
	return nil
}
func (TestEntityHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "testentity_history"}, enthistory.Annotations{IsHistory: true, Triggers: []enthistory.OpType{enthistory.OpTypeInsert}}}
}
func (TestEntityHistory) Indexes() []ent.Index {
	return []ent.Index{index.Fields("history_time")}
}
