// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TestEntitiesColumns holds the columns for the "test_entities" table.
	TestEntitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"started", "success"}, Default: "started"},
	}
	// TestEntitiesTable holds the schema information for the "test_entities" table.
	TestEntitiesTable = &schema.Table{
		Name:       "test_entities",
		Columns:    TestEntitiesColumns,
		PrimaryKey: []*schema.Column{TestEntitiesColumns[0]},
	}
	// TestentityHistoryColumns holds the columns for the "testentity_history" table.
	TestentityHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "ref", Type: field.TypeInt, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"started", "success"}, Default: "started"},
	}
	// TestentityHistoryTable holds the schema information for the "testentity_history" table.
	TestentityHistoryTable = &schema.Table{
		Name:       "testentity_history",
		Columns:    TestentityHistoryColumns,
		PrimaryKey: []*schema.Column{TestentityHistoryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "testentityhistory_history_time",
				Unique:  false,
				Columns: []*schema.Column{TestentityHistoryColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TestEntitiesTable,
		TestentityHistoryTable,
	}
)

func init() {
	TestentityHistoryTable.Annotation = &entsql.Annotation{
		Table: "testentity_history",
	}
}
