// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/schema"
	"entdemo/ent/testentityhistory"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	testentityFields := schema.TestEntity{}.Fields()
	_ = testentityFields
	testentityhistoryFields := schema.TestEntityHistory{}.Fields()
	_ = testentityhistoryFields
	// testentityhistoryDescHistoryTime is the schema descriptor for history_time field.
	testentityhistoryDescHistoryTime := testentityhistoryFields[0].Descriptor()
	// testentityhistory.DefaultHistoryTime holds the default value on creation for the history_time field.
	testentityhistory.DefaultHistoryTime = testentityhistoryDescHistoryTime.Default.(func() time.Time)
}
