// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/testentity"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestEntityQuery is the builder for querying TestEntity entities.
type TestEntityQuery struct {
	config
	ctx        *QueryContext
	order      []testentity.OrderOption
	inters     []Interceptor
	predicates []predicate.TestEntity
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TestEntityQuery builder.
func (teq *TestEntityQuery) Where(ps ...predicate.TestEntity) *TestEntityQuery {
	teq.predicates = append(teq.predicates, ps...)
	return teq
}

// Limit the number of records to be returned by this query.
func (teq *TestEntityQuery) Limit(limit int) *TestEntityQuery {
	teq.ctx.Limit = &limit
	return teq
}

// Offset to start from.
func (teq *TestEntityQuery) Offset(offset int) *TestEntityQuery {
	teq.ctx.Offset = &offset
	return teq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (teq *TestEntityQuery) Unique(unique bool) *TestEntityQuery {
	teq.ctx.Unique = &unique
	return teq
}

// Order specifies how the records should be ordered.
func (teq *TestEntityQuery) Order(o ...testentity.OrderOption) *TestEntityQuery {
	teq.order = append(teq.order, o...)
	return teq
}

// First returns the first TestEntity entity from the query.
// Returns a *NotFoundError when no TestEntity was found.
func (teq *TestEntityQuery) First(ctx context.Context) (*TestEntity, error) {
	nodes, err := teq.Limit(1).All(setContextOp(ctx, teq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{testentity.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (teq *TestEntityQuery) FirstX(ctx context.Context) *TestEntity {
	node, err := teq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TestEntity ID from the query.
// Returns a *NotFoundError when no TestEntity ID was found.
func (teq *TestEntityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(1).IDs(setContextOp(ctx, teq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testentity.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (teq *TestEntityQuery) FirstIDX(ctx context.Context) int {
	id, err := teq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TestEntity entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TestEntity entity is found.
// Returns a *NotFoundError when no TestEntity entities are found.
func (teq *TestEntityQuery) Only(ctx context.Context) (*TestEntity, error) {
	nodes, err := teq.Limit(2).All(setContextOp(ctx, teq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{testentity.Label}
	default:
		return nil, &NotSingularError{testentity.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (teq *TestEntityQuery) OnlyX(ctx context.Context) *TestEntity {
	node, err := teq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TestEntity ID in the query.
// Returns a *NotSingularError when more than one TestEntity ID is found.
// Returns a *NotFoundError when no entities are found.
func (teq *TestEntityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = teq.Limit(2).IDs(setContextOp(ctx, teq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testentity.Label}
	default:
		err = &NotSingularError{testentity.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (teq *TestEntityQuery) OnlyIDX(ctx context.Context) int {
	id, err := teq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestEntities.
func (teq *TestEntityQuery) All(ctx context.Context) ([]*TestEntity, error) {
	ctx = setContextOp(ctx, teq.ctx, "All")
	if err := teq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TestEntity, *TestEntityQuery]()
	return withInterceptors[[]*TestEntity](ctx, teq, qr, teq.inters)
}

// AllX is like All, but panics if an error occurs.
func (teq *TestEntityQuery) AllX(ctx context.Context) []*TestEntity {
	nodes, err := teq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TestEntity IDs.
func (teq *TestEntityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if teq.ctx.Unique == nil && teq.path != nil {
		teq.Unique(true)
	}
	ctx = setContextOp(ctx, teq.ctx, "IDs")
	if err = teq.Select(testentity.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (teq *TestEntityQuery) IDsX(ctx context.Context) []int {
	ids, err := teq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (teq *TestEntityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, teq.ctx, "Count")
	if err := teq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, teq, querierCount[*TestEntityQuery](), teq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (teq *TestEntityQuery) CountX(ctx context.Context) int {
	count, err := teq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (teq *TestEntityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, teq.ctx, "Exist")
	switch _, err := teq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (teq *TestEntityQuery) ExistX(ctx context.Context) bool {
	exist, err := teq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TestEntityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (teq *TestEntityQuery) Clone() *TestEntityQuery {
	if teq == nil {
		return nil
	}
	return &TestEntityQuery{
		config:     teq.config,
		ctx:        teq.ctx.Clone(),
		order:      append([]testentity.OrderOption{}, teq.order...),
		inters:     append([]Interceptor{}, teq.inters...),
		predicates: append([]predicate.TestEntity{}, teq.predicates...),
		// clone intermediate query.
		sql:  teq.sql.Clone(),
		path: teq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status testentity.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TestEntity.Query().
//		GroupBy(testentity.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (teq *TestEntityQuery) GroupBy(field string, fields ...string) *TestEntityGroupBy {
	teq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TestEntityGroupBy{build: teq}
	grbuild.flds = &teq.ctx.Fields
	grbuild.label = testentity.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status testentity.Status `json:"status,omitempty"`
//	}
//
//	client.TestEntity.Query().
//		Select(testentity.FieldStatus).
//		Scan(ctx, &v)
func (teq *TestEntityQuery) Select(fields ...string) *TestEntitySelect {
	teq.ctx.Fields = append(teq.ctx.Fields, fields...)
	sbuild := &TestEntitySelect{TestEntityQuery: teq}
	sbuild.label = testentity.Label
	sbuild.flds, sbuild.scan = &teq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TestEntitySelect configured with the given aggregations.
func (teq *TestEntityQuery) Aggregate(fns ...AggregateFunc) *TestEntitySelect {
	return teq.Select().Aggregate(fns...)
}

func (teq *TestEntityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range teq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, teq); err != nil {
				return err
			}
		}
	}
	for _, f := range teq.ctx.Fields {
		if !testentity.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if teq.path != nil {
		prev, err := teq.path(ctx)
		if err != nil {
			return err
		}
		teq.sql = prev
	}
	return nil
}

func (teq *TestEntityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TestEntity, error) {
	var (
		nodes = []*TestEntity{}
		_spec = teq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TestEntity).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TestEntity{config: teq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, teq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (teq *TestEntityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := teq.querySpec()
	_spec.Node.Columns = teq.ctx.Fields
	if len(teq.ctx.Fields) > 0 {
		_spec.Unique = teq.ctx.Unique != nil && *teq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, teq.driver, _spec)
}

func (teq *TestEntityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(testentity.Table, testentity.Columns, sqlgraph.NewFieldSpec(testentity.FieldID, field.TypeInt))
	_spec.From = teq.sql
	if unique := teq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if teq.path != nil {
		_spec.Unique = true
	}
	if fields := teq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testentity.FieldID)
		for i := range fields {
			if fields[i] != testentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := teq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := teq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := teq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := teq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (teq *TestEntityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(teq.driver.Dialect())
	t1 := builder.Table(testentity.Table)
	columns := teq.ctx.Fields
	if len(columns) == 0 {
		columns = testentity.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if teq.sql != nil {
		selector = teq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if teq.ctx.Unique != nil && *teq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range teq.predicates {
		p(selector)
	}
	for _, p := range teq.order {
		p(selector)
	}
	if offset := teq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := teq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestEntityGroupBy is the group-by builder for TestEntity entities.
type TestEntityGroupBy struct {
	selector
	build *TestEntityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tegb *TestEntityGroupBy) Aggregate(fns ...AggregateFunc) *TestEntityGroupBy {
	tegb.fns = append(tegb.fns, fns...)
	return tegb
}

// Scan applies the selector query and scans the result into the given value.
func (tegb *TestEntityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tegb.build.ctx, "GroupBy")
	if err := tegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestEntityQuery, *TestEntityGroupBy](ctx, tegb.build, tegb, tegb.build.inters, v)
}

func (tegb *TestEntityGroupBy) sqlScan(ctx context.Context, root *TestEntityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tegb.fns))
	for _, fn := range tegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tegb.flds)+len(tegb.fns))
		for _, f := range *tegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TestEntitySelect is the builder for selecting fields of TestEntity entities.
type TestEntitySelect struct {
	*TestEntityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tes *TestEntitySelect) Aggregate(fns ...AggregateFunc) *TestEntitySelect {
	tes.fns = append(tes.fns, fns...)
	return tes
}

// Scan applies the selector query and scans the result into the given value.
func (tes *TestEntitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tes.ctx, "Select")
	if err := tes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestEntityQuery, *TestEntitySelect](ctx, tes.TestEntityQuery, tes, tes.inters, v)
}

func (tes *TestEntitySelect) sqlScan(ctx context.Context, root *TestEntityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tes.fns))
	for _, fn := range tes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
