// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/testentity"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestEntityUpdate is the builder for updating TestEntity entities.
type TestEntityUpdate struct {
	config
	hooks    []Hook
	mutation *TestEntityMutation
}

// Where appends a list predicates to the TestEntityUpdate builder.
func (teu *TestEntityUpdate) Where(ps ...predicate.TestEntity) *TestEntityUpdate {
	teu.mutation.Where(ps...)
	return teu
}

// SetStatus sets the "status" field.
func (teu *TestEntityUpdate) SetStatus(t testentity.Status) *TestEntityUpdate {
	teu.mutation.SetStatus(t)
	return teu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (teu *TestEntityUpdate) SetNillableStatus(t *testentity.Status) *TestEntityUpdate {
	if t != nil {
		teu.SetStatus(*t)
	}
	return teu
}

// Mutation returns the TestEntityMutation object of the builder.
func (teu *TestEntityUpdate) Mutation() *TestEntityMutation {
	return teu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (teu *TestEntityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, teu.sqlSave, teu.mutation, teu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (teu *TestEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := teu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (teu *TestEntityUpdate) Exec(ctx context.Context) error {
	_, err := teu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (teu *TestEntityUpdate) ExecX(ctx context.Context) {
	if err := teu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (teu *TestEntityUpdate) check() error {
	if v, ok := teu.mutation.Status(); ok {
		if err := testentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TestEntity.status": %w`, err)}
		}
	}
	return nil
}

func (teu *TestEntityUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := teu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(testentity.Table, testentity.Columns, sqlgraph.NewFieldSpec(testentity.FieldID, field.TypeInt))
	if ps := teu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := teu.mutation.Status(); ok {
		_spec.SetField(testentity.FieldStatus, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, teu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	teu.mutation.done = true
	return n, nil
}

// TestEntityUpdateOne is the builder for updating a single TestEntity entity.
type TestEntityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestEntityMutation
}

// SetStatus sets the "status" field.
func (teuo *TestEntityUpdateOne) SetStatus(t testentity.Status) *TestEntityUpdateOne {
	teuo.mutation.SetStatus(t)
	return teuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (teuo *TestEntityUpdateOne) SetNillableStatus(t *testentity.Status) *TestEntityUpdateOne {
	if t != nil {
		teuo.SetStatus(*t)
	}
	return teuo
}

// Mutation returns the TestEntityMutation object of the builder.
func (teuo *TestEntityUpdateOne) Mutation() *TestEntityMutation {
	return teuo.mutation
}

// Where appends a list predicates to the TestEntityUpdate builder.
func (teuo *TestEntityUpdateOne) Where(ps ...predicate.TestEntity) *TestEntityUpdateOne {
	teuo.mutation.Where(ps...)
	return teuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (teuo *TestEntityUpdateOne) Select(field string, fields ...string) *TestEntityUpdateOne {
	teuo.fields = append([]string{field}, fields...)
	return teuo
}

// Save executes the query and returns the updated TestEntity entity.
func (teuo *TestEntityUpdateOne) Save(ctx context.Context) (*TestEntity, error) {
	return withHooks(ctx, teuo.sqlSave, teuo.mutation, teuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (teuo *TestEntityUpdateOne) SaveX(ctx context.Context) *TestEntity {
	node, err := teuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (teuo *TestEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := teuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (teuo *TestEntityUpdateOne) ExecX(ctx context.Context) {
	if err := teuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (teuo *TestEntityUpdateOne) check() error {
	if v, ok := teuo.mutation.Status(); ok {
		if err := testentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TestEntity.status": %w`, err)}
		}
	}
	return nil
}

func (teuo *TestEntityUpdateOne) sqlSave(ctx context.Context) (_node *TestEntity, err error) {
	if err := teuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testentity.Table, testentity.Columns, sqlgraph.NewFieldSpec(testentity.FieldID, field.TypeInt))
	id, ok := teuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := teuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testentity.FieldID)
		for _, f := range fields {
			if !testentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := teuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := teuo.mutation.Status(); ok {
		_spec.SetField(testentity.FieldStatus, field.TypeEnum, value)
	}
	_node = &TestEntity{config: teuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, teuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	teuo.mutation.done = true
	return _node, nil
}
