// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/testentity"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestEntityCreate is the builder for creating a TestEntity entity.
type TestEntityCreate struct {
	config
	mutation *TestEntityMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (tec *TestEntityCreate) SetStatus(t testentity.Status) *TestEntityCreate {
	tec.mutation.SetStatus(t)
	return tec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tec *TestEntityCreate) SetNillableStatus(t *testentity.Status) *TestEntityCreate {
	if t != nil {
		tec.SetStatus(*t)
	}
	return tec
}

// Mutation returns the TestEntityMutation object of the builder.
func (tec *TestEntityCreate) Mutation() *TestEntityMutation {
	return tec.mutation
}

// Save creates the TestEntity in the database.
func (tec *TestEntityCreate) Save(ctx context.Context) (*TestEntity, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TestEntityCreate) SaveX(ctx context.Context) *TestEntity {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TestEntityCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TestEntityCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TestEntityCreate) defaults() {
	if _, ok := tec.mutation.Status(); !ok {
		v := testentity.DefaultStatus
		tec.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TestEntityCreate) check() error {
	if _, ok := tec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TestEntity.status"`)}
	}
	if v, ok := tec.mutation.Status(); ok {
		if err := testentity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TestEntity.status": %w`, err)}
		}
	}
	return nil
}

func (tec *TestEntityCreate) sqlSave(ctx context.Context) (*TestEntity, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TestEntityCreate) createSpec() (*TestEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &TestEntity{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(testentity.Table, sqlgraph.NewFieldSpec(testentity.FieldID, field.TypeInt))
	)
	if value, ok := tec.mutation.Status(); ok {
		_spec.SetField(testentity.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// TestEntityCreateBulk is the builder for creating many TestEntity entities in bulk.
type TestEntityCreateBulk struct {
	config
	err      error
	builders []*TestEntityCreate
}

// Save creates the TestEntity entities in the database.
func (tecb *TestEntityCreateBulk) Save(ctx context.Context) ([]*TestEntity, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TestEntity, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TestEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TestEntityCreateBulk) SaveX(ctx context.Context) []*TestEntity {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TestEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TestEntityCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
