// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/predicate"
	"entdemo/ent/testentityhistory"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TestEntityHistoryQuery is the builder for querying TestEntityHistory entities.
type TestEntityHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []testentityhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.TestEntityHistory
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TestEntityHistoryQuery builder.
func (tehq *TestEntityHistoryQuery) Where(ps ...predicate.TestEntityHistory) *TestEntityHistoryQuery {
	tehq.predicates = append(tehq.predicates, ps...)
	return tehq
}

// Limit the number of records to be returned by this query.
func (tehq *TestEntityHistoryQuery) Limit(limit int) *TestEntityHistoryQuery {
	tehq.ctx.Limit = &limit
	return tehq
}

// Offset to start from.
func (tehq *TestEntityHistoryQuery) Offset(offset int) *TestEntityHistoryQuery {
	tehq.ctx.Offset = &offset
	return tehq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tehq *TestEntityHistoryQuery) Unique(unique bool) *TestEntityHistoryQuery {
	tehq.ctx.Unique = &unique
	return tehq
}

// Order specifies how the records should be ordered.
func (tehq *TestEntityHistoryQuery) Order(o ...testentityhistory.OrderOption) *TestEntityHistoryQuery {
	tehq.order = append(tehq.order, o...)
	return tehq
}

// First returns the first TestEntityHistory entity from the query.
// Returns a *NotFoundError when no TestEntityHistory was found.
func (tehq *TestEntityHistoryQuery) First(ctx context.Context) (*TestEntityHistory, error) {
	nodes, err := tehq.Limit(1).All(setContextOp(ctx, tehq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{testentityhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) FirstX(ctx context.Context) *TestEntityHistory {
	node, err := tehq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TestEntityHistory ID from the query.
// Returns a *NotFoundError when no TestEntityHistory ID was found.
func (tehq *TestEntityHistoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tehq.Limit(1).IDs(setContextOp(ctx, tehq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testentityhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) FirstIDX(ctx context.Context) int {
	id, err := tehq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TestEntityHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TestEntityHistory entity is found.
// Returns a *NotFoundError when no TestEntityHistory entities are found.
func (tehq *TestEntityHistoryQuery) Only(ctx context.Context) (*TestEntityHistory, error) {
	nodes, err := tehq.Limit(2).All(setContextOp(ctx, tehq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{testentityhistory.Label}
	default:
		return nil, &NotSingularError{testentityhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) OnlyX(ctx context.Context) *TestEntityHistory {
	node, err := tehq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TestEntityHistory ID in the query.
// Returns a *NotSingularError when more than one TestEntityHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (tehq *TestEntityHistoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tehq.Limit(2).IDs(setContextOp(ctx, tehq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testentityhistory.Label}
	default:
		err = &NotSingularError{testentityhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := tehq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestEntityHistories.
func (tehq *TestEntityHistoryQuery) All(ctx context.Context) ([]*TestEntityHistory, error) {
	ctx = setContextOp(ctx, tehq.ctx, "All")
	if err := tehq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TestEntityHistory, *TestEntityHistoryQuery]()
	return withInterceptors[[]*TestEntityHistory](ctx, tehq, qr, tehq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) AllX(ctx context.Context) []*TestEntityHistory {
	nodes, err := tehq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TestEntityHistory IDs.
func (tehq *TestEntityHistoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tehq.ctx.Unique == nil && tehq.path != nil {
		tehq.Unique(true)
	}
	ctx = setContextOp(ctx, tehq.ctx, "IDs")
	if err = tehq.Select(testentityhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) IDsX(ctx context.Context) []int {
	ids, err := tehq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tehq *TestEntityHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tehq.ctx, "Count")
	if err := tehq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tehq, querierCount[*TestEntityHistoryQuery](), tehq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) CountX(ctx context.Context) int {
	count, err := tehq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tehq *TestEntityHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tehq.ctx, "Exist")
	switch _, err := tehq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tehq *TestEntityHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := tehq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TestEntityHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tehq *TestEntityHistoryQuery) Clone() *TestEntityHistoryQuery {
	if tehq == nil {
		return nil
	}
	return &TestEntityHistoryQuery{
		config:     tehq.config,
		ctx:        tehq.ctx.Clone(),
		order:      append([]testentityhistory.OrderOption{}, tehq.order...),
		inters:     append([]Interceptor{}, tehq.inters...),
		predicates: append([]predicate.TestEntityHistory{}, tehq.predicates...),
		// clone intermediate query.
		sql:  tehq.sql.Clone(),
		path: tehq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TestEntityHistory.Query().
//		GroupBy(testentityhistory.FieldHistoryTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tehq *TestEntityHistoryQuery) GroupBy(field string, fields ...string) *TestEntityHistoryGroupBy {
	tehq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TestEntityHistoryGroupBy{build: tehq}
	grbuild.flds = &tehq.ctx.Fields
	grbuild.label = testentityhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//	}
//
//	client.TestEntityHistory.Query().
//		Select(testentityhistory.FieldHistoryTime).
//		Scan(ctx, &v)
func (tehq *TestEntityHistoryQuery) Select(fields ...string) *TestEntityHistorySelect {
	tehq.ctx.Fields = append(tehq.ctx.Fields, fields...)
	sbuild := &TestEntityHistorySelect{TestEntityHistoryQuery: tehq}
	sbuild.label = testentityhistory.Label
	sbuild.flds, sbuild.scan = &tehq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TestEntityHistorySelect configured with the given aggregations.
func (tehq *TestEntityHistoryQuery) Aggregate(fns ...AggregateFunc) *TestEntityHistorySelect {
	return tehq.Select().Aggregate(fns...)
}

func (tehq *TestEntityHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tehq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tehq); err != nil {
				return err
			}
		}
	}
	for _, f := range tehq.ctx.Fields {
		if !testentityhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tehq.path != nil {
		prev, err := tehq.path(ctx)
		if err != nil {
			return err
		}
		tehq.sql = prev
	}
	return nil
}

func (tehq *TestEntityHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TestEntityHistory, error) {
	var (
		nodes = []*TestEntityHistory{}
		_spec = tehq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TestEntityHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TestEntityHistory{config: tehq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tehq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tehq *TestEntityHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tehq.querySpec()
	_spec.Node.Columns = tehq.ctx.Fields
	if len(tehq.ctx.Fields) > 0 {
		_spec.Unique = tehq.ctx.Unique != nil && *tehq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tehq.driver, _spec)
}

func (tehq *TestEntityHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(testentityhistory.Table, testentityhistory.Columns, sqlgraph.NewFieldSpec(testentityhistory.FieldID, field.TypeInt))
	_spec.From = tehq.sql
	if unique := tehq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tehq.path != nil {
		_spec.Unique = true
	}
	if fields := tehq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testentityhistory.FieldID)
		for i := range fields {
			if fields[i] != testentityhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tehq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tehq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tehq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tehq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tehq *TestEntityHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tehq.driver.Dialect())
	t1 := builder.Table(testentityhistory.Table)
	columns := tehq.ctx.Fields
	if len(columns) == 0 {
		columns = testentityhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tehq.sql != nil {
		selector = tehq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tehq.ctx.Unique != nil && *tehq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tehq.predicates {
		p(selector)
	}
	for _, p := range tehq.order {
		p(selector)
	}
	if offset := tehq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tehq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestEntityHistoryGroupBy is the group-by builder for TestEntityHistory entities.
type TestEntityHistoryGroupBy struct {
	selector
	build *TestEntityHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tehgb *TestEntityHistoryGroupBy) Aggregate(fns ...AggregateFunc) *TestEntityHistoryGroupBy {
	tehgb.fns = append(tehgb.fns, fns...)
	return tehgb
}

// Scan applies the selector query and scans the result into the given value.
func (tehgb *TestEntityHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tehgb.build.ctx, "GroupBy")
	if err := tehgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestEntityHistoryQuery, *TestEntityHistoryGroupBy](ctx, tehgb.build, tehgb, tehgb.build.inters, v)
}

func (tehgb *TestEntityHistoryGroupBy) sqlScan(ctx context.Context, root *TestEntityHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tehgb.fns))
	for _, fn := range tehgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tehgb.flds)+len(tehgb.fns))
		for _, f := range *tehgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tehgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tehgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TestEntityHistorySelect is the builder for selecting fields of TestEntityHistory entities.
type TestEntityHistorySelect struct {
	*TestEntityHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tehs *TestEntityHistorySelect) Aggregate(fns ...AggregateFunc) *TestEntityHistorySelect {
	tehs.fns = append(tehs.fns, fns...)
	return tehs
}

// Scan applies the selector query and scans the result into the given value.
func (tehs *TestEntityHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tehs.ctx, "Select")
	if err := tehs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestEntityHistoryQuery, *TestEntityHistorySelect](ctx, tehs.TestEntityHistoryQuery, tehs, tehs.inters, v)
}

func (tehs *TestEntityHistorySelect) sqlScan(ctx context.Context, root *TestEntityHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tehs.fns))
	for _, fn := range tehs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tehs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tehs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
