// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TestEntity is the predicate function for testentity builders.
type TestEntity func(*sql.Selector)

// TestEntityHistory is the predicate function for testentityhistory builders.
type TestEntityHistory func(*sql.Selector)
